# Generated by Django 3.1.13 on 2021-08-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybershop', '0002_auto_20210813_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancel_request',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=15)),
                ('desc', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
