# Generated by Django 3.1.13 on 2021-08-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybershop', '0003_cancel_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=15)),
                ('desc', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='cancel_request',
        ),
    ]
