# Generated by Django 3.1.13 on 2021-08-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybershop', '0004_auto_20210814_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact2',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
