# Generated by Django 3.1.13 on 2021-08-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybershop', '0005_contact2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cancel',
            new_name='Cancelrequest',
        ),
        migrations.DeleteModel(
            name='Contact2',
        ),
    ]
