# Generated by Django 3.1.13 on 2021-08-17 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybershop', '0006_auto_20210814_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancelrequest',
            old_name='order_id',
            new_name='ord',
        ),
    ]
